cc -c -O -I/usr/local/include checkoff.c
cc -c -O -I/usr/local/include cleanup.c
cc -c -O -I/usr/local/include coordtrans.c
cc -c -O -I/usr/local/include copyzoom.c
cc -c -O -I/usr/local/include dokey.c
cc -c -O -I/usr/local/include doseeing.c
cc -c -O -I/usr/local/include doslit.c
cc -c -O -I/usr/local/include drawline.c
cc -c -O -I/usr/local/include exposebmwin.c
cc -c -O -I/usr/local/include exposecmap.c
cc -c -O -I/usr/local/include exposesee.c
cc -c -O -I/usr/local/include figdisp.c
cc -c -O -I/usr/local/include figcurs.c
cc -c -O -I/usr/local/include getdata.c
cc -c -O -I/usr/local/include getvisuals.c
cc -c -O -I/usr/local/include handlexevent.c
cc -c -O -I/usr/local/include initbmcmap.c
cc -c -O -I/usr/local/include initbmdata.c
cc -c -O -I/usr/local/include initbmluts.c
cc -c -O -I/usr/local/include initbmwin.c
cc -c -O -I/usr/local/include initcmapwin.c
cc -c -O -I/usr/local/include initgc.c
cc -c -O -I/usr/local/include initlocwin.c
cc -c -O -I/usr/local/include initpatchwin.c
cc -c -O -I/usr/local/include initseewin.c
cc -c -O -I/usr/local/include lwwrite.c
cc -c -O -I/usr/local/include panloc.c
cc -c -O -I/usr/local/include panpatch.c
cc -c -O -I/usr/local/include printhelp.c
cc -c -O -I/usr/local/include proccom.c
cc -c -O -I/usr/local/include redrawim.c
cc -c -O -I/usr/local/include resdb.c
cc -c -O -I/usr/local/include resizebmwin.c
cc -c -O -I/usr/local/include resizecmap.c
cc -c -O -I/usr/local/include resizeim.c
cc -c -O -I/usr/local/include resizeloc.c
cc -c -O -I/usr/local/include seehester.c
cc -c -O -I/usr/local/include transim.c
cc -c -O -I/usr/local/include transluts.c
cc -c -O -I/usr/local/include updateloc.c
cc -c -O -I/usr/local/include updatepatch.c
cc -c -O -I/usr/local/include updatetitle.c
cc -c -O -I/usr/local/include writeim.c
cc -c -O -I/usr/local/include writeim16.c
cc -c -O -I/usr/local/include writeluts.c
cc -c -O -I/usr/local/include zoomim.c
cc -c -O -I/usr/local/include exposelgwin.c
cc -c -O -I/usr/local/include getcolors.c
cc -c -O -I/usr/local/include initlgluts.c
cc -c -O -I/usr/local/include initlgwin.c
cc -c -O -I/usr/local/include initlock.c
cc -c -O -I/usr/local/include initwmattr.c
cc -c -O -I/usr/local/include mainloop.c
cc -c -O -I/usr/local/include resizelgwin.c
cc -c -O -I/usr/local/include returnbuf.c
cc -c -O -I/usr/local/include waitevent.c
cc -c -O -I/usr/local/include updatelgtitle.c
cc -o figdisp -O -I/usr/local/include -Bstatic checkoff.o cleanup.o coordtrans.o copyzoom.o dokey.o doseeing.o doslit.o drawline.o exposebmwin.o exposecmap.o exposesee.o figdisp.o figcurs.o getdata.o getvisuals.o handlexevent.o initbmcmap.o initbmdata.o initbmluts.o initbmwin.o initcmapwin.o initgc.o initlocwin.o initpatchwin.o initseewin.o lwwrite.o panloc.o panpatch.o printhelp.o proccom.o redrawim.o resdb.o resizebmwin.o resizecmap.o resizeim.o resizeloc.o seehester.o transim.o transluts.o updateloc.o updatepatch.o updatetitle.o writeim.o writeim16.o writeluts.o zoomim.o exposelgwin.o getcolors.o initlgluts.o initlgwin.o initlock.o initwmattr.o mainloop.o resizelgwin.o returnbuf.o waitevent.o updatelgtitle.o -lX11 -lm
