
/* Generated by Interface Builder */

#import <objc/Object.h>
#import "PGObject.h"
#import "PGView.h"
#import "pgvListener.h"
//#import "pgvSpeaker.h"

@interface Dispatch:Object
{
   id newPGObject;
   Listener *myListener;
   PGView *curView;
//   id    mySpeaker;
//   port_t thePort;
}

- newWindow:sender;

@end
