
/* Generated by Interface Builder */

#import <appkit/View.h>

@interface PGView:View
{
   short i2pos[1000][2]; /* coords of the userpath used to draw graph */
   short bbox[4];	/* bounding box of graph - minx, miny, maxx, maxy */
   int   numPoints;	/* number of points in the graph */
//   char cops[1000];	/* operator array of the userpath used to draw graph */
   char  *cops;
   char  *pecops;
   int   iclear;
   int   iopt;
   float width,gray;
}

- drawSelf:(const NXRect *) rects :(int)rectCount;
- clear;
- dopsop: (int) iop at: (int) n1 and:(int) n2;
- eofill;
- flush;
- linewidth: (double) dwidth;
- setgray: (double) dgray;

@end
