C*GREXEC -- PGPLOT device handler dispatch routine
C+
      SUBROUTINE GREXEC(IDEV,IFUNC,RBUF,NBUF,CHR,LCHR)
      INTEGER IDEV, IFUNC, NBUF, LCHR
      REAL    RBUF(*)
      CHARACTER*(*) CHR
C---
      INTEGER NDEV
      PARAMETER (NDEV=9)
      CHARACTER*10 MSG
C---
      GOTO(1,2,3,4,5,6,7,8,9) IDEV
      IF (IDEV.EQ.0) THEN
          RBUF(1) = NDEV
          NBUF = 1
      ELSE
          WRITE (MSG,'(I10)') IDEV
          CALL GRQUIT('Unknown device code in GREXEC: '//MSG)
      END IF
      RETURN
C---
    1 CALL GFDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    2 CALL GTDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    3 CALL NUDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    4 CALL PSDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    5 CALL REDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
C--- 
C   MODIFIED TO CALL THE GL DRIVER WHEN COMPILED ON THE IRIS
C
    6 CALL IRDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    7 CALL TEDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    8 CALL VPDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
    9 CALL VTDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
C
      END
